name: Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install deps
        run: yarn install

      - name: Initialize git user
        run: |
          git config --global user.email "sjeong1127@gmail.com"
          git config --global user.name "Publish Workflow"

      - name: Initialize NPM configuration
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run release
        run: yarn release --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: End message
        run: echo 'Done install deps'
